# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

# Logging
CONFIG_SERIAL=n
CONFIG_LOG=n

# BLE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_DEVICE_NAME="L2E1"

# PMIC drivers
CONFIG_MFD=y
CONFIG_REGULATOR=y
CONFIG_SENSOR=y
