# STEP 1.1 - Disable serial output and enable the Bluetooth LE stack and libraries
CONFIG_SERIAL=n         # Do not initialize UART logger module
CONFIG_BT=y             # Bluetooth LE stack and libraries