
CONFIG_NRFX_TIMER=y
CONFIG_NRFX_PWM=y
CONFIG_NRFX_GPPI=y

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

CONFIG_ASSERT=y
CONFIG_GPIO=y

#STEP 1.2 Enable pattern execution
CONFIG_PATTERN_TIMER_W_CPU=y

#STEP 2.1 Enable PWM simple pattern execution
#CONFIG_PATTERN_PWM_SIMPLE=y

#STEP 3.1 Enable PWM advanced pattern execution
#CONFIG_PATTERN_PWM_COMPLEX=y