CONFIG_GPIO=y
CONFIG_NRFX_GPPI=y
CONFIG_NRFX_TIMER=y
CONFIG_PM_DEVICE=y

CONFIG_PWM=y

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

# STEP 2.1 - Enable system timer to trigger pattern
# STEP 3.2 - Disable system timer as the pattern trigger

# STEP 3.1 - Enable DPPI connection
# STEP 4.6 - Disable DPPI connection


# STEP 4.1 - Configure the PWM period


# STEP 4.2 - Configure pattern period


# STEP 4.3 - Increase the number of events in the pattern

