#
# Copyright (c) 2018 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Nordic_LBS"

# Enable the LBS service
CONFIG_BT_LBS=y
CONFIG_BT_LBS_POLL_BUTTON=n
CONFIG_DK_LIBRARY=n

CONFIG_PM_DEVICE=n


CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=800       
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=800
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y


# Although it is  possible to combine all the settings, for the purpose of the exercise, it is recommended to enable one at a time (except for the step 7) and test the application. 

#Step 1.1: Enable Serial Port
CONFIG_SERIAL=n

#Step 2.1: Enable Watchdog
CONFIG_WATCHDOG=n

#Step 3.1: Enable peripheral domain TIMER at 1MHz
CONFIG_NRFX_TIMER20_1MHz=n

#Step 4.1: Enable MCU power domain TIMER at 1MHz
CONFIG_NRFX_TIMER00_1MHz=n
#Step 5.1: Enable MCU power domain TIMER at 128MHz
CONFIG_NRFX_TIMER00_128MHz=n


#Step 6.1: Enable peripheral PWM
CONFIG_PWM=n

#Step 7.1
CONFIG_PWM=y
CONFIG_SERIAL=y

#Step 8.1: Enable GRT PWM
CONFIG_NRFX_PWM_GRTC=y





