CONFIG_GPIO=y
CONFIG_NRFX_GPPI=y
CONFIG_NRFX_TIMER=y
CONFIG_PM_DEVICE=y

CONFIG_PWM=y

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n



#STEP 3.1 Enable DPPI connection
CONFIG_USE_PPI_WORKFLOW=y
 
#STEP 4.2 Configure the PWM period
CONFIG_PWM_OUTPUT_PERIOD_US=100

#STEP 4.3 Configure pattern period
CONFIG_GPIO_EVENT_PERIOD_US=10

#STEP 4.6 Disable DPPI connection
CONFIG_USE_PPI_WORKFLOW=n
 