#
# Copyright (c) 2018 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="Nordic_LBS"

# Enable the LBS service
CONFIG_BT_LBS=y
CONFIG_BT_LBS_POLL_BUTTON=n
CONFIG_DK_LIBRARY=n

CONFIG_PM_DEVICE=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=800       
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=800
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y

# Although it is possible to combine all the settings, for the purpose of the exercise it is recommended to enable one at a time.

# STEP 2.1 - Enable the watchdog peripheral


# STEP 3.1 - Enable the serial console driver
# STEP 4.4 - Disable the serial console driver
CONFIG_SERIAL=n

# STEP 4.1 - Enable peripheral domain TIMER20 at 1 MHz


# STEP 5.1 - Enable MCU domain TIMER00 at 1 MHz


# STEP 6.1 - Enable MCU domain TIMER00 at 128 MHz


# STEP 7.1 - Enable the PWM peripheral


# STEP 8.2 - Enable the GRTC PWM output

