CONFIG_GPIO=y
CONFIG_NRFX_GPPI=y
CONFIG_NRFX_TIMER=y

CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

CONFIG_PM_DEVICE=y

CONFIG_PWM=y

#STEP 3.1 Enable DPPI connection

 
#STEP 4.2 Configure the PWM period


#STEP 4.3 Configure pattern period


#STEP 4.6 Disable DPPI connection
